### ISSUE TITLE
Inquiry Regarding the Release Date of the Dataset

### ISSUE THREAD

**Issue by DumoeDss** [llm-jp/llm-jp-sft#27]
Hello! I am interest in the Japanese dataset mentioned in your project. This dataset would be extremely valuable for my research and work. If possible, could you please inform me about the release date or any progress on it? Thank you very much for your assistance and effort!

こんにちは！貴プロジェクトに記載されている日本語データセットに非常に関心を持っています。このデータセットは私の研究と仕事に非常に役立つでしょう。可能であれば、公開日や進捗状況について教えていただけますか？ご協力とご尽力に心から感謝いたします！

**Comment by hkiyomaru** [comment]
Sorry for the late reply. We've released instruction datasets. Please refer to the following page for details.
https://llm-jp.nii.ac.jp/release/#%E3%83%81%E3%83%A5%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0%E3%83%87%E3%83%BC%E3%82%BF
